export const dummyStats = {
  totalOrders: 325,
  totalRevenue: 125430.75,
  avgOrderSize: 385.94,
  pendingPayment: 18,
}

export const dummyOrders = [
  {
    order_id: 'ord_001',
    order_number: '#49652',
    order_type: 'fitment_centre',
    created_at: '2026-05-11T12:35:00Z',
    currency: 'AUD',
    payment_status: 'paid',
    order_status: 'processing',
    shipping_cost: 0,
    gst_amount: 5.40,
    discount_amount: 10,
    total_amount: 598.00,
    notes: 'Customer requested careful handling during transport.',
    fitment_id: 'fitment_001',
    customers: {
      customer_id: 'cust_001',
      first_name: 'Shagun',
      last_name: 'Tyagi',
      email: 'shagun@example.com',
      phone: '0400250175',
      created_at: '2025-06-15T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '38 Porter St',
      city: 'Hemmant',
      state: 'QLD',
      postal_code: '4174',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_001', quantity: 2, unit_price: 299, skus: { sku: 'MIC-PS5-22545R17', tyre_size_display: 'Michelin Pilot Sport 5 225/45R17' } },
    ],
    fitment_job: {
      task_number: 'FIT-49652-001',
      scheduled_date: '2026-05-15',
      scheduled_time: '10:00 AM',
      job_status: 'tyres_dispatched',
      fitment_centres: { business_name: 'Onyx Shield Brisbane' },
    },
    order_shipments: [],
    order_payments: [
      { payment_id: 'pay_001', payment_reference: 'ER75VY1', created_at: '2026-05-11T12:35:25Z', payment_method: 'stripe', status: 'paid', amount: 598.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_001', event_type: 'order_paid', description: 'Payment confirmed', amount: 598.00, currency: 'AUD', created_at: '2026-05-11T12:36:00Z' },
      { activity_id: 'act_002', event_type: 'order_placed', description: 'Order placed', amount: 598.00, currency: 'AUD', created_at: '2026-05-11T12:35:00Z' },
    ],
  },

  {
    order_id: 'ord_002',
    order_number: '#49653',
    order_type: 'home_delivery',
    created_at: '2026-05-11T09:15:00Z',
    currency: 'AUD',
    payment_status: 'paid',
    order_status: 'fulfilled',
    shipping_cost: 15,
    gst_amount: 85.09,
    discount_amount: 0,
    total_amount: 936.00,
    notes: 'Leave package near front door.',
    fitment_id: null,
    customers: {
      customer_id: 'cust_002',
      first_name: 'Ali',
      last_name: 'Khan',
      email: 'ali.khan@example.com',
      phone: '0411223344',
      created_at: '2025-02-10T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '12 Oxford Street',
      city: 'Sydney',
      state: 'NSW',
      postal_code: '2000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_003', quantity: 4, unit_price: 225, skus: { sku: 'MICH-PS5-235R18', tyre_size_display: 'Michelin Pilot Sport 5 235/40R18' } },
    ],
    fitment_job: null,
    order_shipments: [
      {
        shipment_id: 'ship_001',
        status: 'delivered',
        tracking_number: 'TRK-938271645',
        tracking_uri: 'https://tracking.example.com/TRK-938271645',
        shipped_at: '2026-05-11T14:00:00Z',
        delivered_at: '2026-05-12T10:30:00Z',
        warehouses: { warehouse_name: 'Sydney Main Warehouse' },
      },
    ],
    order_payments: [
      { payment_id: 'pay_002', payment_reference: 'PAY-936', created_at: '2026-05-11T09:20:00Z', payment_method: 'stripe', status: 'paid', amount: 936.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_003', event_type: 'order_delivered', description: 'Package delivered', amount: null, currency: 'AUD', created_at: '2026-05-12T10:30:00Z' },
      { activity_id: 'act_004', event_type: 'order_shipped', description: 'Shipment dispatched', amount: null, currency: 'AUD', created_at: '2026-05-11T14:00:00Z' },
    ],
  },

  {
    order_id: 'ord_003',
    order_number: '#49654',
    order_type: 'fitment_centre',
    created_at: '2026-05-10T08:00:00Z',
    currency: 'AUD',
    payment_status: 'partially_paid',
    order_status: 'pending',
    shipping_cost: 0,
    gst_amount: 64.82,
    discount_amount: 15,
    total_amount: 713.00,
    notes: 'Technician should call customer 30 mins before arrival.',
    fitment_id: 'fitment_003',
    customers: {
      customer_id: 'cust_003',
      first_name: 'David',
      last_name: 'Lee',
      email: 'david.lee@example.com',
      phone: '0400111222',
      created_at: '2024-11-05T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '12 Logan Road',
      city: 'Brisbane',
      state: 'QLD',
      postal_code: '4120',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_005', quantity: 4, unit_price: 182, skus: { sku: 'CONT-SC7-22540R18', tyre_size_display: 'Continental SportContact 7 225/40R18' } },
    ],
    fitment_job: {
      task_number: 'FIT-003',
      scheduled_date: '2026-05-14',
      scheduled_time: '11:00 AM',
      job_status: 'customer_notified',
      fitment_centres: { business_name: 'Onyx Shield Melbourne CBD' },
    },
    order_shipments: [],
    order_payments: [
      { payment_id: 'pay_003', payment_reference: 'PARTIAL-300', created_at: '2026-05-10T08:15:00Z', payment_method: 'bank_transfer', status: 'pending', amount: 300, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_005', event_type: 'partial_payment', description: 'Customer paid deposit', amount: 300, currency: 'AUD', created_at: '2026-05-10T08:15:00Z' },
    ],
  },

  {
    order_id: 'ord_004',
    order_number: '#49655',
    order_type: 'home_delivery',
    created_at: '2026-05-10T14:22:00Z',
    currency: 'AUD',
    payment_status: 'unpaid',
    order_status: 'pending',
    shipping_cost: 20,
    gst_amount: 47.45,
    discount_amount: 0,
    total_amount: 541.80,
    notes: null,
    fitment_id: null,
    customers: {
      customer_id: 'cust_004',
      first_name: 'Priya',
      last_name: 'Sharma',
      email: 'priya.sharma@example.com',
      phone: '0422334455',
      created_at: '2025-09-20T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '5 Collins Street',
      city: 'Melbourne',
      state: 'VIC',
      postal_code: '3000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_007', quantity: 2, unit_price: 249, skus: { sku: 'GY-EF1A6-24535R19', tyre_size_display: 'Goodyear Eagle F1 Asymmetric 6 245/35R19' } },
    ],
    fitment_job: null,
    order_shipments: [],
    order_payments: [],
    order_activity: [
      { activity_id: 'act_007', event_type: 'order_placed', description: 'Order placed', amount: 541.80, currency: 'AUD', created_at: '2026-05-10T14:22:00Z' },
    ],
  },

  {
    order_id: 'ord_005',
    order_number: '#49656',
    order_type: 'fitment_centre',
    created_at: '2026-05-09T11:05:00Z',
    currency: 'AUD',
    payment_status: 'paid',
    order_status: 'fulfilled',
    shipping_cost: 0,
    gst_amount: 119.27,
    discount_amount: 50,
    total_amount: 1262.00,
    notes: 'VIP customer — priority booking.',
    fitment_id: 'fitment_002',
    customers: {
      customer_id: 'cust_005',
      first_name: 'James',
      last_name: 'Walker',
      email: 'james.walker@example.com',
      phone: '0433445566',
      created_at: '2024-03-01T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '88 Pitt Street',
      city: 'Sydney',
      state: 'NSW',
      postal_code: '2000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_009', quantity: 4, unit_price: 309, skus: { sku: 'PIR-PZ-27535R21', tyre_size_display: 'Pirelli P Zero 275/35R21' } },
    ],
    fitment_job: {
      task_number: 'FIT-005',
      scheduled_date: '2026-05-10',
      scheduled_time: '02:00 PM',
      job_status: 'completed',
      fitment_centres: { business_name: 'Onyx Shield Sydney North' },
    },
    order_shipments: [],
    order_payments: [
      { payment_id: 'pay_005', payment_reference: 'PAY-1262', created_at: '2026-05-09T11:10:00Z', payment_method: 'stripe', status: 'paid', amount: 1262.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_009', event_type: 'job_completed', description: 'Fitment job completed', amount: null, currency: 'AUD', created_at: '2026-05-10T16:00:00Z' },
      { activity_id: 'act_010', event_type: 'order_paid', description: 'Payment confirmed', amount: 1262.00, currency: 'AUD', created_at: '2026-05-09T11:10:00Z' },
    ],
  },

  {
    order_id: 'ord_006',
    order_number: '#49657',
    order_type: 'home_delivery',
    created_at: '2026-05-09T07:30:00Z',
    currency: 'AUD',
    payment_status: 'refunded',
    order_status: 'refunded',
    shipping_cost: 15,
    gst_amount: 27.18,
    discount_amount: 0,
    total_amount: 314.00,
    notes: 'Customer changed mind — full refund issued.',
    fitment_id: null,
    customers: {
      customer_id: 'cust_006',
      first_name: 'Emma',
      last_name: 'Wilson',
      email: 'emma.wilson@example.com',
      phone: '0455667788',
      created_at: '2025-07-14T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '3 Queen Street',
      city: 'Brisbane',
      state: 'QLD',
      postal_code: '4000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_011', quantity: 2, unit_price: 149.50, skus: { sku: 'BRI-T005-20555R16', tyre_size_display: 'Bridgestone Turanza T005 205/55R16' } },
    ],
    fitment_job: null,
    order_shipments: [],
    order_payments: [
      { payment_id: 'pay_006', payment_reference: 'REF-314', created_at: '2026-05-09T09:00:00Z', payment_method: 'stripe', status: 'refunded', amount: 314.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_011', event_type: 'order_refunded', description: 'Full refund processed', amount: 314.00, currency: 'AUD', created_at: '2026-05-09T09:00:00Z' },
    ],
  },

  {
    order_id: 'ord_007',
    order_number: '#49658',
    order_type: 'fitment_centre',
    created_at: '2026-05-08T15:45:00Z',
    currency: 'AUD',
    payment_status: 'paid',
    order_status: 'paid',
    shipping_cost: 0,
    gst_amount: 87.09,
    discount_amount: 0,
    total_amount: 956.00,
    notes: null,
    fitment_id: 'fitment_004',
    customers: {
      customer_id: 'cust_007',
      first_name: 'Liam',
      last_name: 'Chen',
      email: 'liam.chen@example.com',
      phone: '0466778899',
      created_at: '2025-04-22T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '99 Hay Street',
      city: 'Perth',
      state: 'WA',
      postal_code: '6000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_013', quantity: 4, unit_price: 239, skus: { sku: 'HAN-S1E3-23540R18', tyre_size_display: 'Hankook Ventus S1 Evo3 235/40R18' } },
    ],
    fitment_job: {
      task_number: 'FIT-007',
      scheduled_date: '2026-05-12',
      scheduled_time: '09:00 AM',
      job_status: 'pending',
      fitment_centres: { business_name: 'Onyx Shield Perth' },
    },
    order_shipments: [],
    order_payments: [
      { payment_id: 'pay_007', payment_reference: 'PAY-956', created_at: '2026-05-08T15:50:00Z', payment_method: 'stripe', status: 'paid', amount: 956.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_013', event_type: 'order_paid', description: 'Payment confirmed', amount: 956.00, currency: 'AUD', created_at: '2026-05-08T15:50:00Z' },
    ],
  },

  {
    order_id: 'ord_008',
    order_number: '#49659',
    order_type: 'home_delivery',
    created_at: '2026-05-08T10:00:00Z',
    currency: 'AUD',
    payment_status: 'paid',
    order_status: 'processing',
    shipping_cost: 15,
    gst_amount: 34.09,
    discount_amount: 25,
    total_amount: 380.00,
    notes: 'Gift wrap requested.',
    fitment_id: null,
    customers: {
      customer_id: 'cust_008',
      first_name: 'Nadia',
      last_name: 'Hassan',
      email: 'nadia.hassan@example.com',
      phone: '0477889900',
      created_at: '2025-11-03T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '7 Pulteney Street',
      city: 'Adelaide',
      state: 'SA',
      postal_code: '5000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_015', quantity: 2, unit_price: 195, skus: { sku: 'MIC-EN4-19565R15', tyre_size_display: 'Michelin Energy Saver 4 195/65R15' } },
    ],
    fitment_job: null,
    order_shipments: [],
    order_payments: [
      { payment_id: 'pay_008', payment_reference: 'PAY-380', created_at: '2026-05-08T10:05:00Z', payment_method: 'stripe', status: 'paid', amount: 380.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_015', event_type: 'order_paid', description: 'Payment confirmed', amount: 380.00, currency: 'AUD', created_at: '2026-05-08T10:05:00Z' },
    ],
  },

  {
    order_id: 'ord_009',
    order_number: '#49660',
    order_type: 'fitment_centre',
    created_at: '2026-05-07T13:20:00Z',
    currency: 'AUD',
    payment_status: 'paid',
    order_status: 'cancelled',
    shipping_cost: 0,
    gst_amount: 52.36,
    discount_amount: 0,
    total_amount: 576.00,
    notes: 'Cancelled by customer — stock allocated to next order.',
    fitment_id: 'fitment_001',
    customers: {
      customer_id: 'cust_009',
      first_name: 'Ryan',
      last_name: 'Murphy',
      email: 'ryan.murphy@example.com',
      phone: '0488991122',
      created_at: '2025-08-17T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '45 Flinders Street',
      city: 'Melbourne',
      state: 'VIC',
      postal_code: '3000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_017', quantity: 4, unit_price: 144, skus: { sku: 'GY-EF1A5-20555R16', tyre_size_display: 'Goodyear Eagle F1 Asymmetric 5 205/55R16' } },
    ],
    fitment_job: {
      task_number: 'FIT-009',
      scheduled_date: '2026-05-10',
      scheduled_time: '03:00 PM',
      job_status: 'cancelled',
      fitment_centres: { business_name: 'Onyx Shield Brisbane' },
    },
    order_shipments: [],
    order_payments: [
      { payment_id: 'pay_009', payment_reference: 'PAY-576', created_at: '2026-05-07T13:25:00Z', payment_method: 'stripe', status: 'paid', amount: 576.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_017', event_type: 'order_cancelled', description: 'Order cancelled by customer', amount: null, currency: 'AUD', created_at: '2026-05-08T09:00:00Z' },
    ],
  },

  {
    order_id: 'ord_010',
    order_number: '#49661',
    order_type: 'home_delivery',
    created_at: '2026-05-07T08:55:00Z',
    currency: 'AUD',
    payment_status: 'paid',
    order_status: 'fulfilled',
    shipping_cost: 20,
    gst_amount: 158.36,
    discount_amount: 100,
    total_amount: 1680.00,
    notes: null,
    fitment_id: null,
    customers: {
      customer_id: 'cust_010',
      first_name: 'Sophie',
      last_name: 'Martin',
      email: 'sophie.martin@example.com',
      phone: '0499001122',
      created_at: '2024-12-01T00:00:00Z',
    },
    shipping_address_snapshot: {
      address_line1: '22 George Street',
      city: 'Sydney',
      state: 'NSW',
      postal_code: '2000',
      country: 'Australia',
    },
    billing_address_snapshot: {},
    order_items: [
      { order_item_id: 'item_019', quantity: 4, unit_price: 445, skus: { sku: 'PIR-PZ-27540R20', tyre_size_display: 'Pirelli P Zero 275/40R20' } },
    ],
    fitment_job: null,
    order_shipments: [
      {
        shipment_id: 'ship_002',
        status: 'delivered',
        tracking_number: 'TRK-112233445',
        tracking_uri: 'https://tracking.example.com/TRK-112233445',
        shipped_at: '2026-05-07T15:00:00Z',
        delivered_at: '2026-05-09T11:00:00Z',
        warehouses: { warehouse_name: 'Melbourne Distribution Centre' },
      },
    ],
    order_payments: [
      { payment_id: 'pay_010', payment_reference: 'PAY-1680', created_at: '2026-05-07T09:00:00Z', payment_method: 'stripe', status: 'paid', amount: 1680.00, currency: 'AUD' },
    ],
    order_activity: [
      { activity_id: 'act_019', event_type: 'order_delivered', description: 'Package delivered', amount: null, currency: 'AUD', created_at: '2026-05-09T11:00:00Z' },
    ],
  },
]
